name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check cmake version
      run: cmake --version
  
    - name: Build
      run: cd part2 && mkdir build && cd build && cmake .. && make
      
    - name: Run exe
      run: cd part2/bin && ./GAME
