name: CMakeTest

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      #working-directory: ${{github.workspace}}/part2        
      run: cd part2 && mkdir build && cd build && cmake ..
